pep_version: 2.0.0
sample_table: "sample_table.csv"

sample_modifiers:
  derive:
    attributes: [forward, reverse]
    sources:
      FRW: resources/{sample_name}_mergedF.fastq.gz
      REV: resources/{sample_name}_mergedR.fastq.gz